config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => {:registrations => "users/registrations" ,:sessions => "users/sessions" ,:passwords => "users/passwords"}

   root 'homes#index'

  resources :users do     
    collection do 
      put 'reset_password'
      get 'forgot_password'
    end
  end

  resources :recipes  
  resources :static_pages do
    collection do 
      get 'about_us'
    end
  end
  

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @user = User.new
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_carousel_container.html.erb
<section class="container-fluid carousel-container">
  <div class="slideshow">
    <div id="slideshow" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="item active">
          <img src=<%= image_path("carousel/carousel-img-1.png") %> class="img-responsive" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1></h1>
            </div>
          </div>
        </div><!-- /. Item Active -->
        <div class="item">
          <img src=<%= image_path("carousel/carousel-img-2.JPG") %> class="img-responsive" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1></h1>
            </div>
          </div>
        </div><!-- /. Item -->
        <div class="item">
          <img src=<%= image_path("carousel/carousel-img-3.JPG") %> class="img-responsive" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1></h1>
            </div>
          </div>
        </div><!-- /. Item -->
      </div><!-- /. Carousel-Inner -->
      <div class="controlsBlock">
        <div class="controls">
          <div class="carousel-indicators">
            <li data-target="#slideshow" data-slide-to="0" class="active"></li>
            <li data-target="#slideshow" data-slide-to="1"></li>
            <li data-target="#slideshow" data-slide-to="2"></li>
          </div>
        </div>
      </div>
    </div><!-- /# Slideshow .Carousel -->
  </div><!-- /. Slideshow -->
</section><!-- /. Container -->
<div class="clearfix"></div>

app/views/homes/_food_news.html.erb
<section class="container-fluid food_news">
  <h2 class="text-center">Food News</h2>
  <div class="news_snippets">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 news_snippets-1">
      <h3>Eating Spicey Food Linked to Living Longer</h3>
      <div class="text-tiny text-light">Sky News</div>
      <article class="text-light">eating spicy food has been linked to living a longer life. A study analysed the food...</article>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 news_snippets-2">
      <h3>Congress is having a messy food fight over GMO labeling</h3>
      <div class="text-tiny text-light">The Verge</div>
      <article class="text-light">Late last month, the House of Representatives delivered a blow to an...</article>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 news_snippets-3">
      <h3>Want your food to be GMO-free? Labeling law will let you know</h3>
      <div class="text-tiny text-light">M.Live.com</div>
      <article class="text-light">Legislation that has passed the U.S. House will create one nationwide,...</article>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 news_snippets-4">
      <h3>Ready-to-drink meal could put food on chopping block</h3>
      <div class="text-tiny text-light">CBS News</div>
      <article class="text-light">A company called Soylent has started selling what it calls complete meals, re...</article>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 news_snippets-5">
      <h3>Supermarket Wars: Food Price Inflation Returns</h3>
      <div class="text-tiny text-light">Sky News</div>
      <article class="text-light">Rises in the cost of bread and alcoholic drinks helped push overallfood prices...</article>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 news_snippets-6">
      <h3>Food Column: Potlucks, global foods on tap</h3>
      <div class="text-tiny text-light">Pittsburgh Post-Gazette</div>
      <article class="text-light">Farm to Table Pittsburgh presents food-themed activities for kids at Pittsburg...</article>
    </div>  
  </div>
</section>

app/views/homes/_forgot_password_modal.html.erb
<div class="modal-content forgot_password_modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title hidden">Forgot your password?</h4>
  </div>
  <div class="modal-body">
    <div class="forgot_password_form_container col-lg-8 col-md-8 col-sm-8 col-xs-12">
    <div class="password_requested text-center"></div>
    <%= form_tag(reset_password_users_path(), :method=>'put', remote: true ,class: "forgot_password") do  %>

  
    <div class="form-group field">
      <label for="">Enter your registered email</label>
      <input type="email" class="form-control f-form-group" name = "email" id="" placeholder="Email" required=true>
    </div>


    <div class="form-group actions">
      <%= submit_tag("Send me reset password instructions", class:'forgot_password_button')  %>
    </div>
  </div>
    <% end %>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
    <br>
    <div class="text-center"><button class="sign_up fp-sign_up">Sign up</button></div>
    <br>
    <div class="text-center"><button class="log_in fp-sign_in">Log in</button></div>
  </div>
  <div class="clearfix"></div>
</div>

app/views/homes/_main_modal.html.erb
<%@user = User.new%>
<div class="modal fade" id="main_modal">
  <div class="modal-dialog">
    <%= render partial: "devise/sessions/sign_in_form"%>
    <%= render partial: "homes/forgot_password_modal"%>
    <%= render partial: "devise/registrations/sign_up_form"%>
  </div>
</div>

app/views/homes/_popular_articles.html.erb
<section class="container-fluid popular_articles">
  <h2 class="text-center popular_heading">Popular on MiChef</h2>
  <h6 class="text-center popular_sub_heading">See what others are searching for</h6>
  <div class="popular_small">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 popular-1">
      <img class="img-responsive" src="<%=asset_path('popular-1.png')%>">
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 popular-2">
      <img class="img-responsive" src="<%=asset_path('popular-2.png')%>">
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 popular-3">
      <img class="img-responsive" src="<%=asset_path('popular-3.png')%>">
    </div>  
  </div>
  <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 popular_large">
    <img src="<%=asset_path('popular-main.png')%>">
  </div>
</section>

app/views/homes/_upcoming_event.html.erb
<section class="container-fluid upcoming_event">
  <div class="upcoming_event_box">
    <div class="upcoming_event_content">
      <div class="upcoming-1">
        <img src=<%=image_path("upcoming-1.png") %>>
      </div>
      <div class="upcoming-2">
        <img src=<%=image_path("upcoming-2.png") %>>
      </div>
      <div class="upcoming-3">
        <img src=<%=image_path("upcoming-3.png") %>>
      </div>
      <div class="upcoming-4">
        <img src=<%=image_path("upcoming-4.png") %>>
      </div>  
    </div>
  </div>
</section>

app/views/homes/index.html.erb
<%= render partial: "homes/carousel_container"%>
<%= render partial: "homes/popular_articles"%>

<%= render partial: "homes/upcoming_event"%>

<%= render partial: "homes/food_news"%>

<% content_for :endjs do %>
  <script type="text/javascript">
    $(document).ready(function () {
        miObj.homes(<%= raw({:controller => params[:controller], :action => params[:action]}.to_json) %>);
    });
  </script>
<% end %>